'use client';

import React from 'react';
import { Download, FileText, Loader2 } from 'lucide-react';

interface ExportPDFProps {
    reportId: string;
    healthScore: number;
    summary: string;
    tests: Array<{
        test_name: string;
        observed_value: string;
        unit?: string;
        status?: string;
        explanation?: string;
    }>;
    patientName?: string;
}

export default function ExportPDF({
    reportId,
    healthScore,
    summary,
    tests,
    patientName
}: ExportPDFProps) {
    const [exporting, setExporting] = React.useState(false);

    const generatePDF = async () => {
        setExporting(true);

        try {
            // Create printable HTML content
            const content = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Health Report - ${patientName || 'Patient'}</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #4F46E5; padding-bottom: 20px; }
            .header h1 { color: #4F46E5; font-size: 24px; margin-bottom: 5px; }
            .header p { color: #666; font-size: 12px; }
            .score-box { background: linear-gradient(135deg, #4F46E5, #7C3AED); color: white; padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 30px; }
            .score-box h2 { font-size: 48px; margin-bottom: 5px; }
            .score-box p { opacity: 0.9; }
            .summary { background: #F3F4F6; padding: 15px; border-radius: 8px; margin-bottom: 30px; }
            .summary h3 { color: #4F46E5; margin-bottom: 10px; }
            .tests-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
            .tests-table th { background: #4F46E5; color: white; padding: 12px; text-align: left; }
            .tests-table td { padding: 12px; border-bottom: 1px solid #E5E7EB; }
            .tests-table tr:nth-child(even) { background: #F9FAFB; }
            .status-normal { color: #10B981; font-weight: bold; }
            .status-low { color: #F59E0B; font-weight: bold; }
            .status-high { color: #EF4444; font-weight: bold; }
            .footer { text-align: center; color: #9CA3AF; font-size: 10px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #E5E7EB; }
            .disclaimer { background: #FEF3C7; border: 1px solid #F59E0B; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
            .disclaimer p { color: #92400E; font-size: 12px; }
            @media print { body { padding: 20px; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🏥 MedInsight AI</h1>
            <p>Medical Report Analysis</p>
          </div>

          <div class="score-box">
            <h2>${healthScore}%</h2>
            <p>Health Score</p>
          </div>

          <div class="summary">
            <h3>Summary</h3>
            <p>${summary || 'No summary available.'}</p>
          </div>

          <h3 style="margin-bottom: 15px; color: #4F46E5;">Test Results</h3>
          <table class="tests-table">
            <thead>
              <tr>
                <th>Test Name</th>
                <th>Value</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${tests.map(test => `
                <tr>
                  <td>${test.test_name}</td>
                  <td>${test.observed_value} ${test.unit || ''}</td>
                  <td class="status-${(test.status || '').toLowerCase()}">${test.status || 'Unknown'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="disclaimer">
            <p><strong>⚠️ Medical Disclaimer:</strong> This report is generated by AI for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult your healthcare provider with any questions about your health.</p>
          </div>

          <div class="footer">
            <p>Generated by MedInsight AI on ${new Date().toLocaleDateString()}</p>
            <p>Report ID: ${reportId}</p>
          </div>
        </body>
        </html>
      `;

            // Open print dialog
            const printWindow = window.open('', '_blank');
            if (printWindow) {
                printWindow.document.write(content);
                printWindow.document.close();
                printWindow.focus();
                setTimeout(() => {
                    printWindow.print();
                }, 250);
            }
        } catch (err) {
            console.error('Error generating PDF:', err);
            alert('Failed to generate PDF. Please try again.');
        } finally {
            setExporting(false);
        }
    };

    return (
        <button
            onClick={generatePDF}
            disabled={exporting}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white/5 border border-white/10 text-white hover:bg-white/10 transition-colors disabled:opacity-50"
        >
            {exporting ? (
                <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
                <Download className="w-5 h-5" />
            )}
            Export PDF
        </button>
    );
}
